export const VARIANT_OPTIONS = Object.freeze({
    PRODUCT_TYPE : "image",
    SIZE_TYPE : "button",
    PRODUCT_TITLE_3D_CLOTH : 0,
    SIZE_TITLE_3D_CLOTH : 1,
    PRODUCT_TITLE_QUILT : 1,
    SIZE_TITLE_QUILT: 0,
    PRODUCT_TITLE_BLANKET : "Blanket",
    SIZE_TITLE_BLANKET : 0,
    PRODUCT_TITLE_MASK : "3D Mask",
    SIZE_TITLE_MASK : 0,
});